#!/bin/sh
 
### BEGIN INIT INFO
# Provides:          nginx
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the nginx web server
# Description:       starts nginx using start-stop-daemon
### END INIT INFO
 
PATH=/opt/bin:/opt/sbin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

### EDIT HERE
PREFIX_PATH=/home/redmine/nginx
### / EDIT HERE

DAEMON=$PREFIX_PATH/sbin/nginx
PIDFILE=$PREFIX_PATH/logs/nginx.pid
NAME="nginx: master process"
DESC=nginx
 
test -x $DAEMON || exit 0
 
# Include nginx defaults if available
if [ -f /etc/default/nginx ] ; then
        . /etc/default/nginx
fi

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

set -e
 
case "$1" in
  start)
        echo -n "Starting $DESC: "
        start-stop-daemon --start --pidfile $PIDFILE \
                --exec $DAEMON -- $DAEMON_OPTS
        echo "$NAME."
        ;;  
  stop)
        echo -n "Stopping $DESC: "
        start-stop-daemon --stop --pidfile $PIDFILE \
                --exec $DAEMON
        echo "$NAME."
        ;;  
  restart|force-reload)
        echo -n "Restarting $DESC: "
        start-stop-daemon --stop --quiet --pidfile \
                $PIDFILE --exec $DAEMON
        sleep 1
        start-stop-daemon --start --quiet --pidfile \
                $PIDFILE --exec $DAEMON -- $DAEMON_OPTS
        echo "$NAME."
        ;;
  status)
        status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
      ;;
  reload)
      echo -n "Reloading $DESC configuration: "
      start-stop-daemon --stop --signal HUP --pidfile $PIDFILE \
          --exec $DAEMON
      echo "$NAME."
      ;;  
  *)  
        N=/etc/init.d/nginx
        echo "Usage: $N {start|stop|restart|status|reload|force-reload}" >&2
        exit 1
        ;;  
esac
 
exit 0


